### ISSUE TITLE
initrd-0 hanging at 99%

### ISSUE THREAD

**Issue by josdotso** [google/netboot#10]
Hello. 

New to using Pixiecore, but seeing some odd behavior in my experiments and I thought you might be interested.  Hosting CoreOS images inside Pixiecore.  PXE booting a QEMU machine against Pixiecore and the kernel transfers ok but the initrd hangs at 99% the whole time.

My research suggests Pixiecore may not provide a content-length header for the images which is why iPXE skips to 99% .   Chances are my network config is just slow but I found the 99% part worth mentioning.

https://groups.google.com/d/msg/puppet-razor/wgzQzU8fzDY/BLUG4AdnZwsJ

Thoughts?

Thanks!

**Comment by danderson** [comment]
Hot damn, that's what was wrong! I've been beating my head against a wall trying to figure out why CoreOS seemed to take for ever to netboot.

I've built a hacky fix and CoreOS boot time on my pathological case laptop went from "never" to "seconds" with the addition of Content-Length in responses. I'll polish up the change and have it pushed within the hour.

Thanks!

**Comment by josdotso** [comment]
Wow!  Fast turnaround.  Wow! Super fast downloading CoreOS now!.  Thanks!!
