### ISSUE TITLE
Document import path

### ISSUE THREAD

**Issue by groob** [google/netboot#2]
The canonical import for this project is `package dhcp4 // import "go.universe.tf/netboot/dhcp4"`
Is this still true? If so, could you add in the README that this is a mirror? 

For anyone else that runs into the issue: 
https://golang.org/doc/go1.4#canonicalimports

**Comment by danderson** [comment]
Thanks for the report, I've documented the canonical import path in the README.

To also repeat the warning in that readme: all these APIs are very unstable, and I'm probably going to break compatibility at some point, so use with caution :).
