### ISSUE TITLE
API --dhcp-no-bind flag seems invalid

### ISSUE THREAD

**Issue by darryltnz** [google/netboot#20]
Perhaps a silly question here but when attempting to run:

pixiecore api http://127.0.0.1:6000/ --dhcp-no-bind

The following error is produced:

listen ipv4:17: lookup <nil>: invalid domain name

Note: I am attempting to run this inside a Docker container with an OS base of Ubuntu 16.04
I have also tried placing the --dhcp-no-bind flag infront of the api URL and the result is the same.

Am I missing something obvious with the --dhcp-no-bind flag? I am needing this as I am running a dhcp server inside the same container.

**Comment by panchoh** [comment]
I worked around it by specifying a listening address.

See my pull request for more details.

Cheers!

-- 
pancho horrillo

**Comment by panchoh** [comment]
I worked around it by specifying a listening address, like this:

```
$ pixiecore api http://localhost:9090	\
        --dhcp-no-bind			\
        --listen-addr 0.0.0.0
```
See my pull request #15 for more details.

Cheers!
