### ISSUE TITLE
Pixiecore API - Providing Ignition Config Files For CoreOS via cmdline cloud-config-url

### ISSUE THREAD

**Issue by darryltnz** [google/netboot#21]
I can successfully point Pixiecore to a URL specifying a cloud-config.yml file and PXE boot CoreOS machines fine.

I am wanting to point Pixiecore to a URL specifying an Ignition file.

So far I have tried returning a valid URL in the cloud-config-url JSON field within a "cmdline" JSON object but the machines boot and respond with "Failed to start Load cloud-config from URL defined in /proc.cmdline" and my config is not used.

As Ignition is run very early in the boot cycle I have also attempted to pass Pixiecore a first boot parameter as per the "When is Ignition Executed" section of:

https://coreos.com/ignition/docs/latest/what-is-ignition.html.

 I have included this argument in my "cmdline" JSON object as a JSON entry consisting of "coreos.first_boot": "1".

This has had no effect.

I am wondering if there is anything specific that needs to be done to provide Ignition config files or is this not currently possible with Pixiecore?

**Comment by panchoh** [comment]
Hi!

You need to use `coreos.config.url` linux kernel param, instead of `cloud-config-url`.  See [the docs](https://coreos.com/blog/introducing-ignition.html#pxe-amp-bare-metal) for more details.

Hope that it helps.

Cheers!
