### ISSUE TITLE
pixiecore: [not an issue] Pointer to a demo

### ISSUE THREAD

**Issue by panchoh** [google/netboot#22]
Hi!

We demoed pixiecore + waitron usage at the OpenStack Summit that took place on October 2016 in Barcelona.

Here's a pointer to it, in case anybody is interested:

https://www.openstack.org/videos/video/innovation-at-bbva-next-generation-overlay-for-kubernetes-and-openstack

or, directly to the point where the pixiecore demo starts:

https://youtu.be/QyGHZ2HCwqY?t=440

Hope that it helps.

Cheers!

**Comment by danderson** [comment]
Thanks for the pointer! I've added it to a "demos and users" section of the homepage. If you're still using Pixiecore, I'd love to head more about how you're using it :).
