### ISSUE TITLE
pixiecore: deprecated in CoreOS' bootcfg

### ISSUE THREAD

**Issue by panchoh** [google/netboot#25]
Hi.

Just to raise awareness of it, I'll mention that CoreOS has recently deprecated Pixiecore support in their [bootcfg](https://github.com/coreos/coreos-baremetal/tree/master/bootcfg) tool, see [the commit](https://github.com/coreos/coreos-baremetal/commit/1e367634f30ba1b35113e144262801b66051a48a).

The commit message says:
```
Documentation: Deprecate Pixiecore support
* Focus on real-world, varied network environments
and flexibility, and bare-metal Tectonic
* iPXE provides better hardware introspection than being
limited to MAC
* ISC DHCP and dnsmasq provides production DHCP service
* Drop Pixiecore from the setups we can support or recommend
```
Note that the code is still there, but deprecated.

I'm currently using [jhaals/waitron](https://github.com/jhaals/waitron), which has no commits for over a year, but works good enough.

Cheers,

**Comment by danderson** [comment]
That's a pity, but it's their choice I guess.
