### ISSUE TITLE
Running pixiecore on a specific NIC

### ISSUE THREAD

**Issue by hangxie** [google/netboot#27]
I was unable to run pixiecore on any `listen-addr` other than 0.0.0.0, it seems to be the problem from raw socket, this patch works for me:

https://github.com/hangxie/netboot/commit/c8c1e91c96c06cfaa404de113b0d5b3820a49284

The patch forces raw socket listens on all NICs, but filter out those requests from IPs other than `listen-addr`, I believe there should be a solution better than this, but I don't know too much about bpf.

**Comment by hangxie** [comment]
Here are logs:
```
2017/01/04 23:17:25 [DHCP] Offering to boot 80:e0:1d:d7:2a:5c
2017/01/04 23:17:25 [DHCP] Ignore request from unexpected NIC enp21s0/10.10.10.86
2017/01/04 23:17:25 [DHCP] Offering to boot 80:e0:1d:d7:2a:5c
2017/01/04 23:17:29 [TFTP] Sent "80:e0:1d:d7:2a:5c/0" to 172.16.10.15:2070
2017/01/04 23:17:29 [TFTP] clamping blocksize to "172.16.10.15:2071": 1456 -> 1450
2017/01/04 23:17:29 [TFTP] Sent "80:e0:1d:d7:2a:5c/0" to 172.16.10.15:2071
2017/01/04 23:17:29 [DHCP] Offering to boot 80:e0:1d:d7:2a:5c
2017/01/04 23:17:29 [DHCP] Ignore request from unexpected NIC enp21s0/10.10.10.86
2017/01/04 23:17:29 [DHCP] Offering to boot 80:e0:1d:d7:2a:5c
2017/01/04 23:17:29 [HTTP] Sending ipxe boot script to 172.16.10.15:15471
```

And netstat:
```
tcp        0      0 172.16.10.30:18081      0.0.0.0:*               LISTEN      28791/pixiecore
udp        0      0 172.16.10.30:69         0.0.0.0:*                           28791/pixiecore
udp        0      0 172.16.10.30:4011       0.0.0.0:*                           28791/pixiecore
raw        0      0 0.0.0.0:17              0.0.0.0:*               7           28791/pixiecore
```

**Comment by panchoh** [comment]
I think this bit me a while a go, but I failed to report it here.  Thanks for reporting and fixing it!

i suggest that you create a pull request with your changes, so that danderson can process it more easily.  Also, note that you will have to sign a "Contributor License Agreement' (CLA).  Don't worry, the googlebot will guide you through it.

Cheers!

**Comment by danderson** [comment]
Thanks for the report! I need to debug some more and figure out why the raw socket behavior is weird. Your patch seems fine, although I will probably write my own by adding more logic to the BPF program, if I can't make the socket work properly.

**Comment by danderson** [comment]
Ah, I suspect I know. My guess is that binding the raw socket to a specific IP filters out broadcast packets, so the dhcp4 package never receives the DHCPDISCOVER. Fortunately, that's easy to fix with a small extension of the BPF program. I'll test that now.

**Comment by danderson** [comment]
@hangxie I think the commit I just pushed fixes `-l` to work correctly. I've tested both with and without `--dhcp-no-bind`, and now I can boot machines with a pixiecore listening on a specific address. Can you confirm?

**Comment by hangxie** [comment]
It works, thanks for the quick fix.
