### ISSUE TITLE
Cannot Get it Running

### ISSUE THREAD

**Issue by tony199555** [google/netboot#37]
I tried using Ubuntu 16.04 and 14.04, it failed to run. When I run the command it will just stop and do nothing, empty line. I open the browser it displayed: 404 page not found.

Then I went on to try docker, which also out of luck. 

Commands that I have tried:
```
sudo pixiecore boot \
  https://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz \
  https://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz \
  --cmdline='coreos.autologin'
```
```
wget https://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz
wget https://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz
sudo pixiecore boot \
  coreos_production_pxe.vmlinuz \
  coreos_production_pxe_image.cpio.gz \
  --cmdline='coreos.autologin'
```
```
sudo docker run \
  --net=host \
  -v /var/images:/image \
  danderson/pixiecore \
    boot /image/coreos_production_pxe.vmlinuz /image/coreos_production_pxe_image.cpio.gz
```
None of them work properly.

I do not think I have done something wrong unless there are dependencies/other stuff that I have missed. Thanks for the help.

**Comment by tony199555** [comment]
Update: I just found out I can use -d to show log
After running the command, this is what it shows:
[Init] Starting Pixiecore goroutines

**Comment by danderson** [comment]
That's all it's supposed to do. Once the goroutines are started, that means it's listening for DHCP traffic from machines that are trying to boot. Machines should netboot from that point on. If they don't, continue running pixiecore with `-d`, and it should print messages if it's receiving DHCP requests but ignoring them for some reason.

If you want the browser UI that's on the homepage, you need to also pass `--status-port 80`, the human UI is disabled by default.

If machines still fail to netboot, and pixiecore with `-d` is not displaying any messages, that means the DHCP traffic is not reaching Pixiecore for some reason. Check that your firewall accepts UDP traffic coming to ports 67 (dhcp), 69 (tftp) and 80 (http). If you're in an enterprise-like network, it's possible the switches are also doing some DHCP filtering and enforcement to prevent rogue DHCP servers. If you think that might be happening, you should talk to your network admins.

**Comment by tony199555** [comment]
Thank you. I see. I am not really familiar with pxe, what url should I use to boot? 
http://ip/xxx?

**Comment by danderson** [comment]
It depends a lot on the machine and its firmware, but usually, if you go into the BIOS settings, one of the boot options will be something like "Network", or the name of your network card. Tell the machine to boot with that, and the rest should be completely automatic, no need to enter URLs or anything.

**Comment by tony199555** [comment]
Have you use vultr before? I am trying pxe with vultr as it support ipxe and it is cheap enough.

**Comment by danderson** [comment]
Pixiecore is not really designed for your use case. Specifically, pixiecore assumes that it controls the entire bootup lifecycle of the machine. On the other hand, Vultr assumes that *it* controls the machine boot, and all you get to do is give it an iPXE URL. So unfortunately, I don't think Pixiecore is going to work for you :(.

As an alternative, I can recommend https://netboot.xyz/ . You can tell Vultr to boot from https://boot.netboot.xyz , and you will get a menu where you can select the OS you want to boot.

**Comment by tony199555** [comment]
My goal was not use on vultr, I want to use it on packet.net, although I don't know if they are the same.

**Comment by tony199555** [comment]
Thank you for bring up netboot.xyz. It works really good with packet and vultr as they are official supported by netboot.xyz.
