### ISSUE TITLE
UEFI boot fails due to missing bzImage feature code

### ISSUE THREAD

**Issue by danderson** [google/netboot#55]
Report pulled from #52 , by @cdata :

---
Hi, I'm new to both Pixiecore and PXE booting in general. As a minor anecdote that I think might be related, I was having trouble booting a small device yesterday and happened upon your conversation as it was unfolding. I tried using several of the "quick" options just to rule out any mistakes I might have made invoking Pixiecore, but the results were the same. Sure enough, rolling back to October 17th in pixiecore enabled my device to load everything and boot.

This may be a completely different issue, but given the title of the issue I figured I would post it in here first since i-dont-know-what-im-doing.jpg.

Attached is a pcap I took using the debug command I found in pixiecore. The device would reboot immediately upon failure to boot, but I was able to glean a reference to this error in the output: http://ipxe.org/3c092083

[boot.pcap.zip](https://github.com/google/netboot/files/1596531/boot.pcap.zip)

I'm not sure how else to be most helpful, but here is a basic description of my setup:

My host machine is a Macbook Pro with VirtualBox. On my host there is a VM with a bridged network adapter, and this VM runs Pixiecore. On my local network there is a small device capable of booting over the network.

**Comment by danderson** [comment]
Okay, looking at the pcap, some vital stats:

- PXE client sends DHCP request, identifies as UEFI x86_64
- Pixiecore responds with x86_64 UEFI iPXE.
- Client downloads the ipxe over TFTP.
- ipxe sends DHCP request.
- **Pixiecore responds incorrectly**, it offers the iPXE TFTP file again, instead of the iPXE boot script.

So, Pixiecore is incorrectly concluding that the booting client is _not_ iPXE.

@cdata for this bug report, were you using the latest "master" build of Pixiecore? I suspect 81fbed is the problem, it's looking for a bzImage feature code from iPXE, and it's possible that the UEFI version of iPXE doesn't advertise support for that. It would be surprising, but... It's possible.

Wireshark incorrectly decodes the iPXE DHCP option, so I need to write a custom decoder to investigate more.

The good news is, the work I'm doing for #51 should fix this unconditionally anyway, but I still want to understand what happened.

**Comment by danderson** [comment]
Okay, here we go. Manually decoding the iPXE features DHCP option, this is the features advertised by iPXE: `DNS, EFI, HTTP, iSCSI, Menu, TFTP, SRP, AoE`

So, as we can see, the embedded iPXE built into Pixiecore does not advertise support for bzImage... So, because of commit 81fbed5acf561320d856017efdd7b593e62d8539, Pixiecore concludes that this is not a valid iPXE, and so tries to chainload iPXE again. And because of #51, it does the chainloading incorrectly, and the boot fails.

So, the root problem here is actually: it looks like I'm incorrectly building iPXE for UEFI, because it's missing bzImage support. I need to find a machine that supports UEFI boot, so that I can check how ipxe behaves when I disable the bzImage check... It used to boot just fine, so I wonder if it just works despite the lack of bzImage feature code.

**Comment by danderson** [comment]
OK, the specific trick here is that EFI iPXE can _only_ boot EFI binaries. The reason linux bzImage _seems_ to work is because the kernels are usually built with CONFIG_EFI_STUB, which makes the bzImage loadable as an EFI binary.

So, the trick is that when booting via EFI, it's okay to be missing the bzImage feature flag.

**Comment by danderson** [comment]
@cdata Can you test a pixiecore build from the bug-51 branch in your setup? I've tested the change on a bunch of systems I have access to locally, and I think it fixes the issue you hit (among others). It would be great if you could verify before I merge into master!

**Comment by cdata** [comment]
For the bug report I believe I was using master, but I would have to double check.

I will try the bug-51 branch today and let you know how it goes.

**Comment by cdata** [comment]
Just tried bug-41 branch. I'm happy to report that it appears to work, and my Azulle is booting happily. Thanks for all the good work on this :)

**Comment by danderson** [comment]
Merged into master. Thanks again for the bug report!
