### ISSUE TITLE
dhcp4: Packet.TransactionID as slice or array of bytes

### ISSUE THREAD

**Issue by mdlayher** [google/netboot#59]
Hello!  From what I can tell, it's not uncommon for transaction IDs to end up as unfriendly strings: `TransactionID:_�37`

Is there a reason that transaction ID can't be either `[4]byte` or just `[]byte` instead?  As of now, I'm doing `hex.EncodeToString([]byte(req.TransactionID))` to get a printable transaction ID.

Thanks again for the package!

**Comment by danderson** [comment]
Yeah, I'm not sure what I was thinking with that decision. []byte seems much more plausible ([4]byte is a bit icky to work with). Send a PR?

**Comment by mdlayher** [comment]
Can do. If you'd prefer, I could also just hex encode the bytes directly and retain the string field.
