### ISSUE TITLE
Allow passing an iPXE script through the API

### ISSUE THREAD

**Issue by danderson** [google/netboot#60]
As discussed in #4, Pixiecore doesn't expose the internals of the boot process by design. Specifically, you're not supposed to know that ipxe is being used to boot things.

... With that said, there are some advanced use cases that benefit from an API mode, but can't be shoehorned into a kernel+initrd. Those use cases really want to just pass a custom ipxe script.

I'm willing to add support for that, with the caveat that it will be explicitly documented as: it may break at any time if we stop using ipxe in the boot chain, it might not work everywhere, and it's the responsibility of the author to provide an ipxe script that does the right things.

**Comment by danderson** [comment]
@masaeedu Does this look like what you wanted?
 https://github.com/google/netboot/blob/5528e16d9398c90cc54d7de7839b97183368f420/pixiecore/README.api.md#custom-ipxe-boot-script

Tell me if that's the API you wanted, and I'll merge the change into master.

**Comment by masaeedu** [comment]
That looks pretty good to me, if you can tell me how to build your branch i
can test it tomorrow. Thanks for looking into this.

**Comment by danderson** [comment]
If the API looks like what you wanted, I'll just merge it into master :)
