### ISSUE TITLE
Unable to boot EFI machine (seems to loop through iPXE)

### ISSUE THREAD

**Issue by jiphex** [google/netboot#77]
I've got Pixiecore working great for BIOS hosts, however when I try and boot the same machine (tested on physical Dell host and a VMWare machine) in EFI mode, I seem to get past the chainloading into iPXE phase of the boot process, but then the boot seems to fail with an "Operation not supported" error:

![enotsup](https://user-images.githubusercontent.com/875/45696468-9a4dad00-bb5b-11e8-962b-d778996df3c8.png)

At this point, the machine has booted from its' own EFI firmware, made a first DHCP request (configuring it to boot iPXE next), the machine has then booted iPXE, so I'd expect the next filename to come back to be the actual kernel that the machine is configured to boot (that PixieCore has gathered via the API). The PixieCore log at this point is here:

```
2018/09/18 14:59:57 [DHCP] Got valid request to boot 24:6e:96:78:44:40 (X64)
2018/09/18 14:59:57 [DHCP] Offering to boot 24:6e:96:78:44:40
2018/09/18 15:00:01 [DHCP] Ignoring packet from 24:6e:96:78:44:40: packet is DHCPREQUEST, not DHCPDISCOVER
2018/09/18 15:00:01 [PXE] Ignoring packet from 24:6e:96:78:44:40 (172.16.4.35:4011): packet is DHCPREQUEST, not DHCPDISCOVER
2018/09/18 15:00:02 [TFTP] clamping blocksize to "172.16.4.35:1295": 1468 -> 1450
2018/09/18 15:00:02 [TFTP] Sent "24:6e:96:78:44:40/7" to 172.16.4.35:1295
2018/09/18 15:00:02 [TFTP] clamping blocksize to "172.16.4.35:1296": 1468 -> 1450
2018/09/18 15:00:02 [TFTP] Sent "24:6e:96:78:44:40/7" to 172.16.4.35:1296
2018/09/18 15:00:13 [DHCP] Got valid request to boot 24:6e:96:78:44:40 (X64)
2018/09/18 15:00:13 [DHCP] Offering to boot 24:6e:96:78:44:40
2018/09/18 15:00:13 [DHCP] Ignoring packet from 24:6e:96:78:44:40: packet is DHCPREQUEST, not DHCPDISCOVER
```

It seems like it's trying to chainload into iPXE _again_ at this point though (from iPXE) - the DHCPOFFER packet that comes back has the boot filename set to "24:6e:96:78:44:40/7". The user-class identifier of the associated DHCPDISCOVER packet is however set to  "pixiecore", so I don't understand why Pixiecore is sending back a basic TFTP response.

I've attached a [zipped pcap](https://github.com/google/netboot/files/2393284/dhcp.zip) of the packets that I think are related to this - these are the DHCPDISCOVER sent by iPXE (containing user-class=pixiecore), then a DHCP offer from the Pixiecore container (172.16.4.225) with the boot filename set to "24:6e:96:78:44:40/7".

**Comment by jiphex** [comment]
Additionally, I notice from the log that it [shows ](https://github.com/google/netboot/blob/cc33920b4f3296801a64d731d269978116f40d92/pixiecore/pxe.go#L52) "Ignoring packet from 24:6e:96:78:44:40 (172.16.4.35:4011): packet is DHCPREQUEST, not DHCPDISCOVER", however a response is sent on udp/4011 containing the TFTP filename ("24:...../7")

**Comment by danderson** [comment]
Ah, yeah, the quay.io images aren't maintained any more. Can you point me to where you found them, so I can remove those references? I should probably also delete the images, but first I want to remove links to them.

As for your problem... If you can reproduce it on a current build of pixiecore, I'm kinda out of ideas. Your firmware got past the most "difficult" bit, from the POV of firmware bugs: it got a network config and grabbed the correct file from TFTP. From there, it should be really smooth sailing, because iPXE is in control and it has nice and predictable behavior.

I did change the exact chainloading mechanics for pixiecore a short time ago, to work around yet more bugs in different firmware, so it's possible you just got unlucky with the version you were using. Let's see if the pixiecore from Docker Hub does the right thing for you.

**Comment by jiphex** [comment]
Thanks a lot, I’ll try it with the Docker Hub image tomorrow. The Quay image is linked from 
https://github.com/google/netboot/tree/master/pixiecore

**Comment by jiphex** [comment]
I seem to get the same errors with the danderson/pixiecore image from the Docker Hub, but it seems like the builds of that image have been failing? https://hub.docker.com/r/danderson/pixiecore/builds/

**Comment by jiphex** [comment]
After rebuilding the Docker image myself from the latest sources, the systems I've been having trouble with both seem to boot without issues.

I had to add a `glide.yaml` file to get the Dockerfile to build.

**Comment by danderson** [comment]
Doh, sounds like I broke the continuous build when I switched to Go module vendoring, and didn't notice. Stupid :(. I'll file a bug to fix that, thanks for figuring it out!
